export const IS_FETCHING = "IS_FETCHING";
export const DONE_FETCHING = "DONE_FETCHING";

export const SHOPS = "SHOPS";
export const SELECTED_SHOP = "SELECTED_SHOP";
export const SHOP_PHOTOS = "SHOP_PHOTOS";
export const USER_SHOPS = "USER_SHOPS";

export const SHOP_REGISTRATION_SUCCESS = "SHOP_REGISTRATION_SUCCESS";
export const SHOP_PHOTO_UPLOAD_SUCCESS = "SHOP_PHOTO_UPLOAD_SUCCESS";
export const SHOP_REGISTRATION_ERROR = "SHOP_REGISTRATION_ERROR";
export const SHOP_PHOTO_UPLOAD_ERROR = "SHOP_PHOTO_UPLOAD_ERROR";

export const USER = "USER";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const USER_REGISTRATION_ERROR = "USER_REGISTRATION_ERROR";

export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
