export const GENDER = [{ key: 0, value: "Male" }, { key: 1, value: "Female" }];

export const CUISINE = [
  { key: 0, value: "American" },
  { key: 1, value: "Arabian" },
  { key: 2, value: "Asian" },
  { key: 3, value: "Beverages" },
  { key: 4, value: "Biryani" },
  { key: 5, value: "British" },
  { key: 6, value: "Cafe" },
  { key: 7, value: "Cantonese" },
  { key: 8, value: "Chinese" },
  { key: 9, value: "Contemporary" },
  { key: 10, value: "Continental" },
  { key: 11, value: "Desserts" },
  { key: 12, value: "Drinks Only" },
  { key: 13, value: "European" },
  { key: 14, value: "Finger" },
  { key: 15, value: "French" },
  { key: 16, value: "Indian" },
  { key: 17, value: "International" },
  { key: 18, value: "Japanese" },
  { key: 19, value: "Juices" },
  { key: 20, value: "Kerala" },
  { key: 21, value: "Korean" },
  { key: 22, value: "Lebanese" },
  { key: 23, value: "Malaysian" },
  { key: 24, value: "Mediterranean" },
  { key: 25, value: "Middle Eastern" },
  { key: 26, value: "Mongolian" },
  { key: 27, value: "Mughlai" },
  { key: 28, value: "North Indian" },
  { key: 29, value: "Pakistani" },
  { key: 30, value: "Pizza" },
  { key: 31, value: "Seafood" },
  { key: 32, value: "South Indian" },
  { key: 33, value: "Sri Lankan" },
  { key: 34, value: "Steak" },
  { key: 35, value: "Thai" },
  { key: 36, value: "Vietnamese" }
];

export const OPENING_HOURS = [
  { key: 0, value: "07.00 am – 10.00 pm (Mon-Sun)" },
  { key: 1, value: "07.00 am – 12.00 pm (Mon-Sun)" },
  { key: 2, value: "08.00 am – 10.00 pm (Mon-Sun)" },
  { key: 3, value: "08.00 am – 12.00 pm (Mon-Sun)" },
  { key: 4, value: "09.00 am – 10.00 pm (Mon-Sun)" },
  { key: 5, value: "09.00 am – 12.00 pm (Mon-Sun)" },
  { key: 6, value: "10.00 am – 10.00 pm (Mon-Sun)" },
  { key: 7, value: "10.00 am – 12.00 pm (Mon-Sun)" },
]